name: Canary-CentOS

on:
  schedule:
    - cron:  '0 16 * * *'
  workflow_dispatch:
    inputs:
      repo-id:
        description: 'staging repository id to test'
        required: false
        default: ''
      djl-version:
        description: 'djl version to test'
        required: false
        default: '0.10.0-SNAPSHOT'

jobs:
  canary-test-centos:

    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      DJL_STAGING: ${{github.event.inputs.repo-id}}
      DJL_VERSION: ${{github.event.inputs.djl-version}}
    container: centos:7
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install libgomp
        run: |
          yum -y install libgomp
      - name: Test MXNet
        working-directory: canary
        run: |
          ./gradlew clean run
          rm -rf ~/.djl.ai
          DJL_ENGINE=mxnet-native-mkl ./gradlew clean run
          rm -rf ~/.djl.ai
      - name: Test PyTorch
        working-directory: canary
        run: |
          DJL_ENGINE=pytorch-native-cpu-precxx11 ./gradlew clean run
          rm -rf ~/.djl.ai
      - name: Test TensorFlow
        working-directory: canary
        run: |
          DJL_ENGINE=tensorflow-native-auto ./gradlew clean run
          rm -rf ~/.djl.ai
          DJL_ENGINE=tensorflow-native-cpu ./gradlew clean run
          rm -rf ~/.djl.ai
      # DLR doesn't support centos 7  
      - name: Test OnnxRuntime
        working-directory: canary
        run: |
          DJL_ENGINE=onnxruntime ./gradlew clean run
