name: Canary-Mac

on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:

jobs:
  canary-test-mac:
    runs-on: macos-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test MXNet
        run: |
          cd canary
          ./gradlew clean run
          rm -rf ~/.djl.ai
          DJL_ENGINE=mxnet-native-mkl ./gradlew clean run
          rm -rf ~/.djl.ai
      - name: Test PyTorch
        run: |
          cd canary
          DJL_ENGINE=pytorch-native-auto ./gradlew clean run
          rm -rf ~/.djl.ai
          DJL_ENGINE=pytorch-native-cpu ./gradlew clean run
          rm -rf ~/.djl.ai
      - name: Test TensorFlow
        run: |
          cd canary
          DJL_ENGINE=tensorflow-native-auto ./gradlew clean run
          rm -rf ~/.djl.ai
          DJL_ENGINE=tensorflow-native-cpu ./gradlew clean run
          rm -rf ~/.djl.ai
      - name: Test DLR
        working-directory: canary
        run: |
          DJL_ENGINE=dlr-native-auto ./gradlew clean run
          rm -rf ~/.djl.ai
          DJL_ENGINE=dlr-native-cpu ./gradlew clean run
          rm -rf ~/.djl.ai
      - name: Test OnnxRuntime
        working-directory: canary
        run: |
          DJL_ENGINE=onnxruntime ./gradlew clean run
